### ISSUE TITLE
in development?

### ISSUE THREAD

**Issue by auser** [alexgorbatchev/angular-injector#1]
How do you handle this in development without getting errors such as:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module Home due to:
ReferenceError: ng is not defined
```

**Comment by kennethlynne** [comment]
AFAIK you can declare a global function that returns its first argument, but it seems dirty.

``` javascript
function ng(fn) { return fn;}
```

**Comment by auser** [comment]
I did, buy feels soooo dirty
    —

**Comment by alexgorbatchev** [comment]
Good point fellas. I actually do generate a `build` folder and run development from there (sourcemaps, etc) so this hasn't been an issue. You could also do something like this

``` javascript
if(env !== 'production') window.ng = function(fn) { return fn; }
```

Still seems like a small trade off for flexibility. I'll update the docs. What do you think?
